env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  # set up awscli packages
  - pip install --user awscli

stages:
  - name: build and deploy
    if: branch = master

jobs:
  include:
    - stage: build and deploy
      script: ./build.sh && ./deploy.sh